(define (problem ejer1_p)
    (:domain ejer1)
    (:objects
        vce1 vce2 - unidad
        marine1 marine2 - unidad
        segador1 - unidad
        centrodemando1 barracon1 extractor1 - edificio
    )
    (:init
        (recurso_edificio Minerales Barracones)
        (recurso_edificio Minerales CentroDeMando)
        (recurso_edificio Gas CentroDeMando)
        (recurso_edificio Minerales Extractor)

        (recurso_unidad Minerales Marine)
        (recurso_unidad Minerales VCE)
        (recurso_unidad Gas Segador)
        (recurso_unidad Minerales Segador)

        (lugar_reclutamiento VCE CentroDeMando)
        (lugar_reclutamiento Marine Barracones)
        (lugar_reclutamiento Segador Barracones)

        (Gas Gas)
        (Minerales Minerales)

        ; Declaro los tipos
        (esTipo_u vce1 VCE)
        (esTipo_u vce2 VCE)
        (esTipo_u marine1 Marine)
        (esTipo_u marine2 Marine)
        (esTipo_u segador1 Segador)
        (esTipo_e centrodemando1 CentroDeMando)
        (esTipo_e barracon1 Barracones)
        (esTipo_e extractor1 Extractor)

        ; Declaro posiciones
        (en_un vce1 T3_4)
        (en_ed centrodemando1 T4_4)
        (nodo_recurso Minerales T2_1)
        (nodo_recurso Minerales T2_5)
        (nodo_recurso Minerales T3_2)
        (nodo_recurso Gas T4_5)
        (nodo_recurso Gas T5_3)

        ; Ninguna unidad ocupada
        (libre vce1)

        ; Tablero
        (conectado T1_1 T1_2)
        (conectado T1_1 T2_1)
        (conectado T1_2 T1_1)
        (conectado T1_2 T1_3)
        (conectado T1_2 T2_2)
        (conectado T1_3 T2_3)
        (conectado T1_3 T1_2)
        (conectado T1_3 T1_4)
        (conectado T1_4 T2_4)
        (conectado T1_4 T1_3)
        (conectado T1_4 T1_5)
        (conectado T1_5 T1_4)
        (conectado T1_5 T2_5)

        (conectado T2_1 T1_1)
        (conectado T2_1 T2_2)
        (conectado T2_1 T3_1)
        (conectado T2_2 T1_2)
        (conectado T2_2 T2_3)
        (conectado T2_2 T3_2)
        (conectado T2_2 T2_1)
        (conectado T2_3 T1_3)
        (conectado T2_3 T3_3)
        (conectado T2_3 T2_2)
        (conectado T2_3 T2_4)
        (conectado T2_4 T1_4)
        (conectado T2_4 T2_3)
        (conectado T2_4 T3_4)
        (conectado T2_4 T2_5)
        (conectado T2_5 T3_5)
        (conectado T2_5 T1_5)
        (conectado T2_5 T2_4)
        
        (conectado T3_1 T2_1)
        (conectado T3_1 T3_2)
        (conectado T3_1 T4_1)
        (conectado T3_2 T2_2)
        (conectado T3_2 T3_3)
        (conectado T3_2 T4_2)
        (conectado T3_2 T3_1)
        (conectado T3_3 T2_3)
        (conectado T3_3 T4_3)
        (conectado T3_3 T3_2)
        (conectado T3_3 T3_4)
        (conectado T3_4 T2_4)
        (conectado T3_4 T4_4)
        (conectado T3_4 T3_5)
        (conectado T3_4 T3_3)
        (conectado T3_5 T2_5)
        (conectado T3_5 T3_4)
        (conectado T3_5 T4_5)
        
        (conectado T4_1 T3_1)
        (conectado T4_1 T5_1)
        (conectado T4_1 T4_2)
        (conectado T4_2 T3_2)
        (conectado T4_2 T4_1)
        (conectado T4_2 T5_2)
        (conectado T4_2 T4_3)
        (conectado T4_3 T3_3)
        (conectado T4_3 T4_4)
        (conectado T4_3 T5_3)
        (conectado T4_3 T4_2)
        (conectado T4_4 T3_4)
        (conectado T4_4 T5_4)
        (conectado T4_4 T4_3)
        (conectado T4_4 T4_5)
        (conectado T4_5 T5_5)
        (conectado T4_5 T3_5)
        (conectado T4_5 T4_4)
        
        (conectado T5_1 T4_1)
        (conectado T5_1 T5_2)
        (conectado T5_2 T4_2)
        (conectado T5_2 T5_3)
        (conectado T5_2 T5_1)
        (conectado T5_3 T4_3)
        (conectado T5_3 T5_4)
        (conectado T5_3 T5_2)
        (conectado T5_4 T4_4)
        (conectado T5_4 T5_3)
        (conectado T5_4 T5_5)
        (conectado T5_5 T4_5)
        (conectado T5_5 T5_4)

        ; Declaro las casillas vacias menos donde hay edificios
        (vacia T1_1)
        (vacia T1_2)
        (vacia T1_3)
        (vacia T1_4)
        (vacia T1_5)

        (vacia T2_1)
        (vacia T2_2)
        (vacia T2_3)
        (vacia T2_4)
        (vacia T2_5)

        (vacia T3_1)
        (vacia T3_2)
        (vacia T3_3)
        (vacia T3_4)
        (vacia T3_5)

        (vacia T4_1)
        (vacia T4_2)
        (vacia T4_3)
        (vacia T4_5)

        (vacia T5_1)
        (vacia T5_2)
        (vacia T5_3)
        (vacia T5_4)
        (vacia T5_5)
    )
    (:goal
        (and
            (en_un marine1 T5_1)
            (en_un marine2 T4_2)
            (en_un segador1 T4_2)
        )
    )
)